# GitHub Sponsors & Funding for LinguaLint
# Support the development of the Responsibility Futures Engine and advanced NLP research

github: jeffy893
patreon: # Replace with Patreon username if you create one
open_collective: # Replace with Open Collective username if you create one
ko_fi: # Replace with Ko-fi username if you create one
tidelift: # Replace with Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with Liberapay username if you create one
issuehunt: # Replace with IssueHunt username if you create one
otechie: # Replace with Otechie username if you create one
lfx_crowdfunding: # Replace with LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://lingualint.com', 'https://jefferson.cloud', 'https://richards.systems', 'https://richards.plus']
